"""Initial schema migration for Hippocampus tables

Revision ID: 20260819_000001
Revises:
Create Date: 2026-08-19 11:03:12.891870
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "20260819_000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('canonical_name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'normalized_name', name='uq_entity_type_normalized_name')
    )
    op.create_index(op.f('ix_entity_entity_type'), 'entity', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_normalized_name'), 'entity', ['normalized_name'], unique=False)
    op.create_table('memory',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_store', sa.String(length=32), nullable=True),
    sa.Column('document_id', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('source_kind', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_status_type', 'memory', ['status', 'memory_type'], unique=False)
    op.create_index('idx_memory_valid_range', 'memory', ['valid_from', 'valid_until'], unique=False)
    op.create_index(op.f('ix_memory_expires_at'), 'memory', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memory_memory_type'), 'memory', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_status'), 'memory', ['status'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('uri', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('ownership', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resource_source_identity', 'resource', ['source_system', 'resource_type', 'external_id'], unique=False)
    op.create_index(op.f('ix_resource_external_id'), 'resource', ['external_id'], unique=False)
    op.create_index(op.f('ix_resource_resource_type'), 'resource', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resource_source_system'), 'resource', ['source_system'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.String(length=192), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('namespace', 'value', name='uq_tag_namespace_value')
    )
    op.create_index(op.f('ix_tag_namespace'), 'tag', ['namespace'], unique=False)
    op.create_index(op.f('ix_tag_value'), 'tag', ['value'], unique=False)
    op.create_table('entity_alias',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=256), nullable=False),
    sa.Column('normalized_alias', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_entity_alias')
    )
    op.create_index(op.f('ix_entity_alias_entity_id'), 'entity_alias', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_alias_normalized_alias'), 'entity_alias', ['normalized_alias'], unique=False)
    op.create_table('memory_embedding',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'model', 'model_version', name='uq_memory_embedding_model')
    )
    op.create_index(op.f('ix_memory_embedding_memory_id'), 'memory_embedding', ['memory_id'], unique=False)
    op.create_table('memory_entity',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'entity_id', 'role', name='uq_memory_entity_role')
    )
    op.create_index(op.f('ix_memory_entity_entity_id'), 'memory_entity', ['entity_id'], unique=False)
    op.create_index(op.f('ix_memory_entity_memory_id'), 'memory_entity', ['memory_id'], unique=False)
    op.create_table('memory_event',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_event_correlation_id'), 'memory_event', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_memory_event_created_at'), 'memory_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_event_event_type'), 'memory_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_memory_event_memory_id'), 'memory_event', ['memory_id'], unique=False)
    op.create_table('memory_provenance',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=True),
    sa.Column('source_resource_id', sa.String(length=64), nullable=True),
    sa.Column('source_memory_id', sa.String(length=64), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('capture_method', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['source_resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_provenance_memory_id'), 'memory_provenance', ['memory_id'], unique=False)
    op.create_table('memory_relationship',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_memory_id', sa.String(length=64), nullable=False),
    sa.Column('target_memory_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_memory_id != target_memory_id', name='ck_relationship_not_self'),
    sa.ForeignKeyConstraint(['source_memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['target_memory_id'], ['memory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_memory_id', 'target_memory_id', 'relation_type', name='uq_memory_relationship')
    )
    op.create_index(op.f('ix_memory_relationship_relation_type'), 'memory_relationship', ['relation_type'], unique=False)
    op.create_index(op.f('ix_memory_relationship_source_memory_id'), 'memory_relationship', ['source_memory_id'], unique=False)
    op.create_index(op.f('ix_memory_relationship_target_memory_id'), 'memory_relationship', ['target_memory_id'], unique=False)
    op.create_table('memory_resource',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('relationship', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'resource_id', 'relationship', name='uq_memory_resource')
    )
    op.create_index(op.f('ix_memory_resource_memory_id'), 'memory_resource', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_resource_resource_id'), 'memory_resource', ['resource_id'], unique=False)
    op.create_table('memory_tag',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'tag_id', name='uq_memory_tag')
    )
    op.create_index(op.f('ix_memory_tag_memory_id'), 'memory_tag', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_tag_tag_id'), 'memory_tag', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_tag_tag_id'), table_name='memory_tag')
    op.drop_index(op.f('ix_memory_tag_memory_id'), table_name='memory_tag')
    op.drop_table('memory_tag')
    op.drop_index(op.f('ix_memory_resource_resource_id'), table_name='memory_resource')
    op.drop_index(op.f('ix_memory_resource_memory_id'), table_name='memory_resource')
    op.drop_table('memory_resource')
    op.drop_index(op.f('ix_memory_relationship_target_memory_id'), table_name='memory_relationship')
    op.drop_index(op.f('ix_memory_relationship_source_memory_id'), table_name='memory_relationship')
    op.drop_index(op.f('ix_memory_relationship_relation_type'), table_name='memory_relationship')
    op.drop_table('memory_relationship')
    op.drop_index(op.f('ix_memory_provenance_memory_id'), table_name='memory_provenance')
    op.drop_table('memory_provenance')
    op.drop_index(op.f('ix_memory_event_memory_id'), table_name='memory_event')
    op.drop_index(op.f('ix_memory_event_event_type'), table_name='memory_event')
    op.drop_index(op.f('ix_memory_event_created_at'), table_name='memory_event')
    op.drop_index(op.f('ix_memory_event_correlation_id'), table_name='memory_event')
    op.drop_table('memory_event')
    op.drop_index(op.f('ix_memory_entity_memory_id'), table_name='memory_entity')
    op.drop_index(op.f('ix_memory_entity_entity_id'), table_name='memory_entity')
    op.drop_table('memory_entity')
    op.drop_index(op.f('ix_memory_embedding_memory_id'), table_name='memory_embedding')
    op.drop_table('memory_embedding')
    op.drop_index(op.f('ix_entity_alias_normalized_alias'), table_name='entity_alias')
    op.drop_index(op.f('ix_entity_alias_entity_id'), table_name='entity_alias')
    op.drop_table('entity_alias')
    op.drop_index(op.f('ix_tag_value'), table_name='tag')
    op.drop_index(op.f('ix_tag_namespace'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_resource_source_system'), table_name='resource')
    op.drop_index(op.f('ix_resource_resource_type'), table_name='resource')
    op.drop_index(op.f('ix_resource_external_id'), table_name='resource')
    op.drop_index('idx_resource_source_identity', table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_memory_status'), table_name='memory')
    op.drop_index(op.f('ix_memory_memory_type'), table_name='memory')
    op.drop_index(op.f('ix_memory_expires_at'), table_name='memory')
    op.drop_index('idx_memory_valid_range', table_name='memory')
    op.drop_index('idx_memory_status_type', table_name='memory')
    op.drop_table('memory')
    op.drop_index(op.f('ix_entity_normalized_name'), table_name='entity')
    op.drop_index(op.f('ix_entity_entity_type'), table_name='entity')
    op.drop_table('entity')
    # ### end Alembic commands ###
